### ISSUE TITLE
high score

### ISSUE THREAD

**Issue by tiffanymagana** [shivamshekhar/Chrome-T-Rex-Rush#1]
getting error message

name 'high_score' is used prior to global declaration??????????????????????????

**Comment by shivamshekhar** [comment]
On line 463, just delete the line `global high_score`, hence on line 463, it should be like
``` Python
if playerDino.score > high_score:   
    high_score = playerDino.score
```

and add `global high_score` at the beginning of your `gameplay()` function, i.e

``` Python
def gameplay():  
    global high_score  
    gamespeed = 4  
    startMenu = False  
    gameOver = False  
    gameQuit = False  
    .
    .
```

I hope that should rectify the error.
