### ISSUE TITLE
Faced with a lot of issues while running a code

### ISSUE THREAD

**Issue by NikQATech** [shivamshekhar/Chrome-T-Rex-Rush#5]
Maybe someone knows, how to fix it?=(

![image](https://user-images.githubusercontent.com/39151564/73666160-6244fc80-46b3-11ea-8b0e-865d1f0d5da3.png)

![image](https://user-images.githubusercontent.com/39151564/73666174-696c0a80-46b3-11ea-8447-6683b56c29e4.png)

**Comment by shivamshekhar** [comment]
Hi,

This seems like an issue with your pygame installation. Are you sure you followed the installation steps properly?

Besides, I could see that you are using Python version 3.8.1.
My suggestion would be to do a clean install of Pygame with Python 2.7 and retry running the script.

Pygame installation instructions : https://www.pygame.org/wiki/GettingStarted#Pygame%20Installation
