### ISSUE TITLE
Thank you for your code! I used for an assigment of fabacademy!

### ISSUE THREAD

**Issue by d-prieto** [shivamshekhar/Chrome-T-Rex-Rush#6]
Hi!

I used this code to open a port with serial.py and talk with a NodeMCU board and control the game with it. The code it's not perfect but I uploaded here (I didn't make a pull request because it's too specific and the code is not clean enough)

Thank you A LOT for sharing the code. 

http://fabacademy.org/2020/labs/barcelona/students/david-prieto/assignments/week16/

**Comment by shivamshekhar** [comment]
Really appreciate this! I am glad my code is of use to people. I wrote this in 3rd year of my university and back then I was a novice in programming (I am still learning though!), so the code might not be highly optimised or well structured.
